//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASPNETbyEddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGerant
    {
        public int idGerant { get; set; }
        public string loginGerant { get; set; }
        public string motDePasseGerant { get; set; }
        public string roleGerant { get; set; }
    
        public virtual tblAdministrateur tblAdministrateur { get; set; }
        public virtual tblDirecteur tblDirecteur { get; set; }
        public virtual tblEmploye tblEmploye { get; set; }
    }
}
